choco install 7zip -y
choco install azure-cli -y
choco install beyondcompare -y
choco install dotnet-6.0-desktopruntime -y
choco install dotnet-7.0-desktopruntime -y
choco install dotnet-7.0-sdk -y
choco install dotnet-8.0-desktopruntime -y
choco install dotnet-8.0-sdk -y
choco install dotnet-sdk -y
choco install dotPeek -y
choco install Firefox -y
choco install git -y
choco install gitextensions -y
choco install googledrive -y
choco install kubernetes-helm -y
choco install linqpad7 -y
choco install microsoft-teams-new-bootstrapper -y
choco install nodejs -y
choco install nordpass -y
choco install octopus-cli -y
choco install perimeter81 -y
choco install postman -y
choco install powershell-core -y
choco install snagit -y
choco install sql-server-management-studio -y
choco install visualstudio2022professional -y
choco install vlc -y
choco install vscode -y
choco install winamp -y
